#!/usr/bin/env zsh

MDTOOL=/Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool

rm -rf bin/*
git submodule foreach git clean -xdf

cd deps/splat
$MDTOOL build -c:Release ./Splat-XamarinStudio.sln
cd -
cp -R deps/splat/**/bin/Release/* ./bin

cd deps/modernhttpclient
make
cd -
cp -R deps/modernhttpclient/src/ModernHttpClient.Android/bin/Release/* ./bin/Monoandroid
cp -R deps/modernhttpclient/src/ModernHttpClient.iOS/bin/Release/* ./bin/Monotouch

cd deps/reactiveui
$MDTOOL build -c:Release ./ReactiveUI_XSAll.sln
cd -
cp -R deps/reactiveui/**/bin/Release/* bin

cp -R bin/MonoMac/* deps/akavache/ext/Mono
cp -R bin/Monoandroid/* deps/akavache/ext/Monodroid
cp -R bin/Monotouch/* deps/akavache/ext/Monotouch

## NB: Because of a Xamarin bug atm, we have to build this 2x
cd deps/akavache
$MDTOOL build -c:Release ./Akavache_XSNoMac.sln
$MDTOOL build -c:Release ./Akavache_XSAll.sln
cd -
cp -R deps/akavache/**/bin/Release/* bin

cp -R bin/Mono/* bin/MonoMac
rm -rf bin/Mono

echo "***** Done! *****"

# vim: ts=4 sw=4 tw=120 et syn=sh :
